project_id = "pgllmekcarufmcznoive"

[functions.bootstrap-admin]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.scheduling-reminder]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.bulk-upload-users]
verify_jwt = false

[functions.bulk-create-staff]
verify_jwt = false

[functions.validate-module-system]
verify_jwt = false

[functions.send-password-otp]
verify_jwt = false

[functions.verify-and-update-password]
verify_jwt = false

[functions.admin-set-password]
verify_jwt = false
